eo-base-helm-chart:
  deployments:
    app:
      replicaCount: 2
      image:
        repository: ghcr.io/energinet-datahub/greenforce-frontend-ett-app
        tag: 0.1.1
        pullPolicy: Always

  service:
    deployment: app
    type: ClusterIP
    port: 80

  ingress:
    hosts: []
    paths:
      - /
    pathExceptions:
      - /api
      - /auth
    servicePort: 80
