# Copyright 2020 Energinet DataHub A/S
#
# Licensed under the Apache License, Version 2.0 (the "License2");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
name: DH UI Frontend Healthchecks
env:
  node-version: 14.x
  node-version-file: .nvmrc
on:
  schedule:
    - cron: '0 * * * *'

jobs:
  healthchecks:
    name: Healthchecks
    runs-on: ubuntu-latest
    steps:
      - name: Check out source code with current branch Git history
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Use Node.js ${{ env.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version-file: ${{ env.node-version-file }}

      - name: Variable-Yarn cache directory path
        id: yarn-cache-dir-path
        run: echo "::set-output name=dir::$(yarn cache dir)"

      - name: Cache Yarn cache directory
        uses: actions/cache@v2
        with:
          path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
          key: ${{ runner.os }}-node-${{ env.node-version }}-yarn-${{
            hashFiles('yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-node-${{ env.node-version }}
            ${{ runner.os }}

      - name: Install package dependencies
        run: yarn install --frozen-lockfile --non-interactive

      - name: Install Playwright
        run: npx playwright install --with-deps

      - name: Run healthchecks
        run: npx nx run e2e-dh:health
