name: Bump Chart and App versions

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  BASE_BRANCH: ${{ github.event.pull_request.base.ref }}
  is-main-branch: ${{ github.ref == 'refs/heads/main' }}
  is-pull-request: ${{ github.event_name == 'pull_request' }}
  NODE_OPTIONS: --max_old_space_size=6144
  node-version-file: .nvmrc
  # keep in sync with "engines.yarn" and "volta.yarn" in "package.json"
  yarn-version: 1.22.19
  NX_MAX_PARALLEL: 2

  # Nx Cloud
  NX_BRANCH: ${{ github.event.number }}
  NX_RUN_GROUP: ${{ github.run_id }}

on:
  push:
    branches:
      - main
  pull_request: {}
  workflow_dispatch: {}

jobs:
  affected:
    name: Is affected?
    runs-on: ubuntu-latest

    outputs:
      is-affected: ${{ steps.affected.outputs.is-affected }}

    steps:
      # needed for nx affected command
      - name: Check out source code with current branch Git history
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      # needed for nx affected command
      - name: 'PR: Fetch base branch Git history'
        if: ${{ env.is-pull-request == 'true' }}
        run: git fetch --no-tags origin $BASE_BRANCH

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version-file: ${{ env.node-version-file }}
          cache: 'yarn'

      - name: Disable workspace NGCC run
        uses: ./.github/actions/setup-postinstall
        with:
          ngcc: false

      - name: Set yarn version ${{ env.yarn-version }}
        run: yarn set version ${{ env.yarn-version }}

      - name: Install package dependencies
        run: yarn install --frozen-lockfile --non-interactive

      - name: Is affected?
        id: affected
        uses: ./.github/actions/affected
        with:
          base: ${{ env.is-main-branch == 'true' && 'HEAD~1' || format('origin/{0}', env.BASE_BRANCH) }}
          project: ${{ env.app-name }}

  bump_helm_chart_version:
    runs-on: ubuntu-latest
    name: Bump Helm chart version
    if: ${{ github.event_name == 'pull_request' && needs.affected.outputs.is-affected == 'true' }}
    needs: affected
    steps:
      - uses: actions/checkout@v3

      - uses: ./.github/actions/yaml-increment-version
        with:
          yaml-file: build/infrastructure/eo/chart/Chart.yaml
          yaml-path: version

  bump_app_version:
    runs-on: ubuntu-latest
    name: Bump App version
    if: ${{ github.event_name == 'pull_request' && needs.affected.outputs.is-affected == 'true' }}
    needs: affected
    steps:
      - uses: actions/checkout@v3

      - uses: ./.github/actions/yaml-increment-version
        with:
          yaml-file: build/infrastructure/eo/chart/values.yaml
          yaml-path: app.image.tag
