name: Changed files

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

on:
  pull_request:
    branches:
      - main
  workflow_dispatch: {}

jobs:
  changedfiles:
    runs-on: ubuntu-latest
    steps:

      - name: Check if dependencies have changed
        id: dependenciesHaveChanged
        uses: ./.github/actions/dependencies-have-changed

      - name: Echo if dependencies have changed
        run: echo "Dependencies have changed ${{ steps.dependenciesHaveChanged.outputs.dependenciesHaveChanged }}"
