name: Cypress Acceptance Tests
on: push
env:
  CYPRESS_DH_BASE_URL: https://jolly-sand-03f839703.azurestaticapps.net
  CYPRESS_DH_E2E_B2C_URL: https://devDataHubB2C.b2clogin.com
  CYPRESS_DH_E2E_USERNAME: ${{ secrets.DH_E2E_U1_USERNAME }}
  CYPRESS_DH_E2E_PASSWORD: ${{ secrets.DH_E2E_U1_PASSWORD }}
  CYPRESS_VIDEOS_FOLDER: ${{ github.workspace }}/apps/dh/e2e-dh/cypress/videos
  CYPRESS_SCREENSHOTS_FOLDER: ${{ github.workspace }}/apps/dh/e2e-dh/cypress/screenshots
  DH_PATH_TO_E2E_TESTS: ${{ github.workspace }}/apps/dh/e2e-dh
jobs:
  cypress-run:
    name: Cypress run
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      # Install npm dependencies, cache them correctly
      # and run all Cypress tests
      - name: Cypress run
        uses: cypress-io/github-action@v6
        with:
          config: baseUrl=${{ env.CYPRESS_DH_BASE_URL }},videosFolder=${{ env.CYPRESS_VIDEOS_FOLDER }},screenshotsFolder=${{ env.CYPRESS_SCREENSHOTS_FOLDER }}
          config-file: cypress-acceptance-tests.config.ts
          working-directory: ${{ env.DH_PATH_TO_E2E_TESTS }} # Use env to reference the environment variable
