on: push
jobs:
  cypress-run:
    name: Cypress run
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      # Install npm dependencies, cache them correctly
      # and run all Cypress tests
      - name: Cypress run
        uses: cypress-io/github-action@v6
        env:
          CYPRESS_DH_E2E_USERNAME: ${{ secrets.DH_E2E_U1_USERNAME }}
          CYPRESS_DH_E2E_PASSWORD: ${{ secrets.DH_E2E_U1_PASSWORD }}
        with:
          config: >
            baseUrl=https://jolly-sand-03f839703.azurestaticapps.net,
            video=true,
            chromeWebSecurity=false,
            supportFile=/src/support/e2e.ts,
            specPattern=/src/**/*.cy.ts,
            fixturesFolder=/src/fixtures,
            excludeSpecPattern=/src/e2e/b2c-healthchecks.cy.ts
          working-directory: ${{ github.workspace }}/apps/dh/e2e-dh
