# Copyright 2020 Energinet DataHub A/S
#
# Licensed under the Apache License, Version 2.0 (the "License2");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
name: GreenForce Frontend CI

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  BASE_BRANCH: ${{ github.event.pull_request.base.ref }}
  is-main-branch: ${{ github.ref == 'refs/heads/main' }}
  is-pull-request: ${{ github.event_name == 'pull_request' }}
  NODE_OPTIONS: --max_old_space_size=6144
  node-version-file: .nvmrc
  # keep in sync with "engines.yarn" and "volta.yarn" in "package.json"
  yarn-version: 1.22.19
  NX_MAX_PARALLEL: 2

  # Nx Cloud
  NX_BRANCH: ${{ github.event.number }}
  NX_CLOUD_ACCESS_TOKEN: ${{ secrets.NX_CLOUD_ACCESS_TOKEN }}
  NX_RUN_GROUP: ${{ github.run_id }}

  # DH E2E
  DH_E2E_USERNAME: ${{ secrets.DH_E2E_USERNAME }}
  DH_E2E_PASSWORD: ${{ secrets.DH_E2E_PASSWORD }}

on:
  push:
    branches:
      - main
    paths-ignore:
      - apps/dh/api-dh/**
      - .github/workflows/api-dh-app-*.yml
  pull_request:
    branches:
      - main
    paths-ignore:
      - apps/dh/api-dh/**
      - .github/workflows/api-dh-app-*.yml
  workflow_dispatch: {}

jobs:
  test:
    name: Unit and integration test
    runs-on: ubuntu-latest

    steps:
      # needed for nx affected command
      - name: 'PR: Check out source code with current branch Git history'
        if: ${{ env.is-pull-request == 'true' }}
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
          ref: ${{ github.head_ref }}
      # needed for nx affected command
      - name: 'PR: Fetch base branch Git history'
        if: ${{ env.is-pull-request == 'true' }}
        run: git fetch --no-tags origin $BASE_BRANCH
      - name: 'Merge: Check out source code'
        if: ${{ env.is-pull-request == 'false' }}
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version-file: ${{ env.node-version-file }}

      - name: Set yarn version ${{ env.yarn-version }}
        run: yarn set version ${{ env.yarn-version }}

      - name: Install package dependencies
        run: yarn install --frozen-lockfile --non-interactive

      - name: 'PR: Test affected projects'
        if: ${{ env.is-pull-request == 'true' }}
        run: yarn affected:test --base=origin/$BASE_BRANCH
          --max-parallel=$NX_MAX_PARALLEL
      - name: 'Merge: Test all projects'
        if: ${{ env.is-pull-request == 'false' }}
        run: yarn test --max-parallel=$NX_MAX_PARALLEL
