name: License Check CI

env:
  BASE_BRANCH: ${{ github.event.pull_request.base.ref }}
  is-main-branch: ${{ github.ref == 'refs/heads/main' }}
  is-pull-request: ${{ github.event_name  == 'pull_request' }}
  NODE_OPTIONS: --max_old_space_size=6144
  node-version: 14.x
  NX_MAX_PARALLEL: 2

  # Nx Cloud
  NX_BRANCH: ${{ github.event.number }}
  NX_RUN_GROUP: ${{ github.run_id }}

on:
  push:
    branches:
      - main
  pull_request: {}
  workflow_dispatch: {}

jobs:
  add-license:
    name: Add license
    runs-on: ubuntu-latest

    steps:
      # needed for nx affected command
      - name: 'PR: Check out source code with current branch Git history'
        if: ${{ env.is-pull-request == 'true' }}
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      # needed for nx affected command
      - name: 'PR: Fetch base branch Git history'
        if: ${{ env.is-pull-request == 'true' }}
        run: git fetch --no-tags --depth=1 origin $BASE_BRANCH
      - name: 'Merge: Check out source code'
        if: ${{ env.is-pull-request == 'false' }}
        uses: actions/checkout@v2

      - name: Debug branch 1
        run: git rev-parse --abbrev-ref HEAD
      - name: Debug branch 2
        run: git branch
      - name: Debug github
        env:
          GITHUB: ${{ toJSON(github) }}
          PULL_REQUEST: ${{ toJSON(github.event.pull_request) }}
        run: |
          echo "$GITHUB"
          echo "$PULL_REQUEST"

      - name: Set up Node.js ${{ env.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ env.node-version }}

      - name: Variable-Yarn cache directory path
        id: yarn-cache-dir-path
        run: echo "::set-output name=dir::$(yarn cache dir)"
      - name: Cache Yarn cache directory
        uses: actions/cache@v2
        with:
          path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
          key: ${{ runner.os }}-node-${{ env.node-version }}-yarn-${{
            hashFiles('yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-node-${{ env.node-version }}
            ${{ runner.os }}
      - name: Install package dependencies
        run: yarn install --frozen-lockfile --non-interactive

      - name: 'PR: Add license to affected projects'
        if: ${{ env.is-pull-request == 'true' }}
        run: yarn affected --target=add-license --base=origin/$BASE_BRANCH
          --max-parallel=$NX_MAX_PARALLEL
      - name: 'Merge: Add license to all projects'
        if: ${{ env.is-pull-request == 'false' }}
        run: yarn nx run-many --target=add-license --all --max-parallel=$NX_MAX_PARALLEL

      - name: Commit licensed files
        run: |
          git config user.name "GitHub Job"
          git config user.email noreply@github.com
          git add -A || true
          git commit -m "chore: add license" || true
          git push origin --force-with-lease || true

  check-license-lines:
    name: Check License Lines
    needs: add-license
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Check License Lines
        uses: kt3k/license_checker@v1.0.3
