# Copyright 2020 Energinet DataHub A/S
#
# Licensed under the Apache License, Version 2.0 (the "License2");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
name: Production Dependencies

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

on:
  push:
    branches:
      - main
    paths-ignore:
      - 'package.json'
      - 'yarn.lock'

  pull_request:
    branches:
      - main
    paths-ignore:
      - 'package.json'
      - 'yarn.lock'
  workflow_dispatch: {}

jobs:
  License_check:
    name: License Check
    runs-on: ubuntu-latest
    steps:
      - run: 'echo "No license check required"'
