name: Production Dependencies

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  node-version-file: .nvmrc
  # keep in sync with "engines.yarn" and "volta.yarn" in "package.json"
  yarn-version: 1.22.19

on:
  pull_request:
    branches:
      - main
  workflow_dispatch: {}

jobs:
  license_check:
    name: License Check
    runs-on: ubuntu-latest

    outputs:
      dependencies-have-changed: ${{ steps.dependencies_have_changed.outputs.dependencies-have-changed }}

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v2
        with:
          node-version-file: ${{ env.node-version-file }}

      - name: Check if dependencies have changed
        id: dependencies_have_changed
        uses: ./.github/actions/dependencies-have-changed

      # Only run steps below if dependencies has changed
      - name: Read .allowed-licenses.json
        id: allowed-licenses
        if: ${{ steps.dependencies_have_changed.outputs.dependencies-have-changed == 'true' }}
        shell: bash
        run: echo ::set-output name=FILE::$(jq -r .[] .allowed-licenses.json | tr '\n' ';')

      - name: Run license-checker
        if: ${{ steps.dependencies_have_changed.outputs.dependencies-have-changed == 'true' }}
        run: npx license-checker-rseidelsohn --direct --summary --production --onlyAllow="${{ steps.allowed-licenses.outputs.FILE }}"
