name: Production Dependencies

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  # keep in sync with "engines.bun" and "volta.bun" in "package.json"
  BUN_VERSION: 1.1.12

on:
  pull_request:
    branches:
      - main
  workflow_dispatch: {}

jobs:
  license_check:
    name: License Check
    runs-on: ubuntu-latest

    outputs:
      dependencies-have-changed: ${{ steps.dependencies_have_changed.outputs.dependencies-have-changed }}

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ref: ${{ github.head_ref }}

      - name: Bun setup
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: ${{ env.BUN_VERSION }}

      - name: Check if dependencies have changed
        id: dependencies_have_changed
        uses: ./.github/actions/dependencies-have-changed

      - name: Install dependencies
        if: ${{ steps.dependencies_have_changed.outputs.dependencies-have-changed == 'true' }}
        run: bun install --frozen-lockfile

      - name: Read .allowed-licenses.json
        id: allowed-licenses
        if: ${{ steps.dependencies_have_changed.outputs.dependencies-have-changed == 'true' }}
        shell: bash
        run: echo "FILE=$(jq -r .[] .allowed-licenses.json | tr '\n' ';')" >> $GITHUB_OUTPUT
      - name: Run license-checker
        id: licenseChecker
        if: ${{ steps.dependencies_have_changed.outputs.dependencies-have-changed == 'true' }}
        run: echo DEPENDENCIES=$(npx license-checker-rseidelsohn@4.2.10 --direct=0 --production --onlyAllow="${{ steps.allowed-licenses.outputs.FILE }}" --json --excludePrivatePackages) >> $GITHUB_OUTPUT
      - name: Update PRODUCTION_DEPENDENCIES.md
        if: ${{ steps.dependencies_have_changed.outputs.dependencies-have-changed == 'true' }}
        uses: ./.github/actions/update-production-dependencies-list
        with:
          dependencies-from-license-checker: ${{ steps.licenseChecker.outputs.DEPENDENCIES }}

      - name: Commit PRODUCTION_DEPENDENCIES.md
        if: ${{ steps.dependencies_have_changed.outputs.dependencies-have-changed == 'true' }}
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add PRODUCTION_DEPENDENCIES.md || cd .
          git commit -m "chore: Update PRODUCTION_DEPENDENCIES.md" || cd .
          git push origin --force-with-lease || cd .
